#!/usr/bin/env bash
# model_switch.sh — per-session inference-substrate switch (3-verb CLI).
#
# Spec: .claude/skills/multi-model-inference-mastery/SKILL.md §3 (the SWITCH).
# HONEST STAMP: the SKILL's mechanism is PROVEN K=1 in the origin civ
# (2026-07-01); THIS script is a NET-NEW implementation for the
# aiciv-fork-template (origin did not ship its scripts upstream).
# Walk-tested (status/peer/default round-trip) on the integration branch;
# UNVALIDATED against a real router until a fork walks §3.4's proof.
#
#   ./tools/model_switch.sh peer     [--reason "text"]   # flip -> peer substrate
#   ./tools/model_switch.sh default  [--reason "text"]   # flip -> default (SAFETY RAIL)
#   ./tools/model_switch.sh status                       # print current mode
#
# State-of-record: config/model_mode.json  {"mode","since","reason","actor","epoch"}
# Env fragment:    config/model_mode.env   (sourced by tools/model_boot.sh)
# Audit log:       logs/model_switch.log
# Router seam (fork wires these — NEVER hardcode a key in this file):
#   config/router_endpoint.txt        the peer router base URL (Anthropic-shaped)
#   config/lifeboat/router_key.txt    the router key, mode 0600 — NEVER echo it
#   config/peer_model_id.txt          the peer model id the router serves
#
# The flip is atomic (tmp+mv). Reversible: every flip backs up the prior state
# to config/model_mode.json.bak.<ts>-pre-<verb>. You cannot get stuck on the
# peer substrate: `default` removes every override.

set -euo pipefail

ROOT="${CIV_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
STATE="$ROOT/config/model_mode.json"
ENVFRAG="$ROOT/config/model_mode.env"
LOG="$ROOT/logs/model_switch.log"
ENDPOINT_FILE="$ROOT/config/router_endpoint.txt"
KEY_FILE="$ROOT/config/lifeboat/router_key.txt"
PEER_MODEL_FILE="$ROOT/config/peer_model_id.txt"

VERB="${1:-status}"
REASON="manual"
if [ "${2:-}" = "--reason" ] && [ -n "${3:-}" ]; then REASON="$3"; fi

mkdir -p "$ROOT/config" "$ROOT/logs"

now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

write_state() { # $1=mode $2=reason
    local ts tmp
    ts="$(now_iso)"
    if [ -f "$STATE" ]; then
        cp "$STATE" "$STATE.bak.$(date -u +%Y%m%dT%H%M%SZ)-pre-$1"
    fi
    tmp="$(mktemp "$STATE.tmp.XXXXXX")"
    printf '{"mode":"%s","since":"%s","reason":"%s","actor":"%s","epoch":%s}\n' \
        "$1" "$ts" "$(printf '%s' "$2" | tr '"' "'" | head -c 200)" \
        "${USER:-unknown}" "$(date -u +%s)" > "$tmp"
    mv "$tmp" "$STATE"   # atomic
    echo "$ts $1 reason=$2" >> "$LOG"
}

case "$VERB" in
    status)
        if [ -f "$STATE" ]; then
            python3 - "$STATE" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
print(f"mode: {d.get('mode','default')}  since: {d.get('since','?')}  reason: {d.get('reason','')}")
PY
        else
            echo "mode: default  (no state file — never flipped)"
        fi
        ;;

    peer)
        # Router seam preflight — refuse to flip into a broken mode.
        MISSING=""
        [ -s "$ENDPOINT_FILE" ] || MISSING="$MISSING $ENDPOINT_FILE"
        [ -s "$KEY_FILE" ]      || MISSING="$MISSING $KEY_FILE"
        [ -s "$PEER_MODEL_FILE" ] || MISSING="$MISSING $PEER_MODEL_FILE"
        if [ -n "$MISSING" ]; then
            echo "REFUSED: peer mode needs the router seam wired first. Missing/empty:$MISSING" >&2
            echo "Wire: router endpoint URL, router key (0600), peer model id. See this script's header." >&2
            exit 2
        fi
        ENDPOINT="$(head -c 300 "$ENDPOINT_FILE" | tr -d '[:space:]')"
        PEER_MODEL="$(head -c 120 "$PEER_MODEL_FILE" | tr -d '[:space:]')"
        # Env fragment: the KEY is read from file AT SOURCE TIME — never inlined here.
        {
            echo "# generated by model_switch.sh $(now_iso) — mode=peer"
            echo "export ANTHROPIC_BASE_URL=\"$ENDPOINT\""
            echo "export ANTHROPIC_MODEL=\"$PEER_MODEL\""
            echo "export CLAUDE_CODE_SUBAGENT_MODEL=\"$PEER_MODEL\""
            echo "export ANTHROPIC_API_KEY=\"\$(cat \"$KEY_FILE\")\""
        } > "$ENVFRAG"
        write_state peer "$REASON"
        echo "mode -> peer (endpoint=$ENDPOINT model=$PEER_MODEL). Flip back: ./tools/model_switch.sh default"
        ;;

    default)
        # trial-m3 flavor: the model is LOCKED to the peer rail (M3 only). A trial
        # civ must never flip itself onto the frontier rail. Operator unlock path:
        #   python3 tools/apply_trial_profile.py convert --restore-models
        if [ -f "$ROOT/config/model_profile.json" ] && \
           python3 -c 'import json,sys; sys.exit(0 if json.load(open(sys.argv[1])).get("locked") is True else 1)' \
               "$ROOT/config/model_profile.json" 2>/dev/null; then
            echo "REFUSED: model is locked by config/model_profile.json (trial-m3 profile: MiniMax-M3 only)." >&2
            echo "Unlocking is an operator act at conversion (profiles/trial-m3/README.md); a trial civ cannot do it." >&2
            exit 3
        fi
        {
            echo "# generated by model_switch.sh $(now_iso) — mode=default"
            echo "unset ANTHROPIC_BASE_URL"
            echo "unset ANTHROPIC_API_KEY"
            echo "# ANTHROPIC_MODEL / CLAUDE_CODE_SUBAGENT_MODEL fall back to .claude/settings.json"
            echo "unset ANTHROPIC_MODEL"
            echo "unset CLAUDE_CODE_SUBAGENT_MODEL"
        } > "$ENVFRAG"
        write_state default "$REASON"
        echo "mode -> default (all peer overrides removed). Safety rail engaged."
        ;;

    *)
        echo "usage: $0 {peer|default|status} [--reason \"text\"]" >&2
        exit 1
        ;;
esac
