#!/usr/bin/env python3
"""
whats_next_to_board.py — verbatim transport from workflow firewall returns to
PROJECT-BOARD.md §0 (the forward-frontier board).

Contract: docs/whats-next-contract.md (§26). The one rule that matters:
**verbatim carry** — this script NEVER derives, ranks, paraphrases, or
LLM-cleans a next-move. The doer-mind judges; the transport carries.

Pipeline (§26.6):
  data/audits/workflow_returns/YYYY-MM/*.json   (firewall-return shards,
                                                 archived by the PostToolUse hook)
    --sweep ->  data/reports/whats-next-feed.jsonl   (append-only ledger)
                data/reports/.whats_next_seen.json   (seen-set; sweep idempotency)
    --regen ->  PROJECT-BOARD.md §0 block between the sentinels
                (upsert one row per project; most-recent ts wins)

Staleness organ (§26.7):
    --canary-check   alert if LAST-GENERATED aged past --max-age-hours (default 4)
                     AND projects-on-frontier > 0. Fail-open; rate-limited
                     (default 6h) via data/reports/.canary_last_alert.

Archive-before-remove rule (PROJECT-BOARD-TEMPLATE.md):
    any row that leaves the §0 block first lands, timestamped, in
    data/board-archive/YYYY-Www-workboard-complete.md via archive_row().

Everything here is fail-open: a broken shard is skipped (and logged),
never wedges the transport.

Provenance stamp (honest): the CONTRACT is LIVE-in-origin (A-C-Gee, 2026-07-02);
this IMPLEMENTATION is net-new for the aiciv-fork-template (origin's transport
tool was not shipped upstream). Self-test: --self-test (runs in a temp root).

CLI:
    python3 tools/whats_next_to_board.py --sweep [--sweep-since-hours N]
    python3 tools/whats_next_to_board.py --regen
    python3 tools/whats_next_to_board.py --sweep-since-hours 168 --regen
    python3 tools/whats_next_to_board.py --canary-check
    python3 tools/whats_next_to_board.py --self-test
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import sys
import tempfile
import uuid
from pathlib import Path

# ---------------------------------------------------------------------------
# Roots (CIV_ROOT env override, else repo root = parent of tools/)
# ---------------------------------------------------------------------------

def _root() -> Path:
    env = os.environ.get("CIV_ROOT") or os.environ.get("AICIV_ROOT")
    if env:
        return Path(env).resolve()
    return Path(__file__).resolve().parent.parent


ROOT = _root()
ARCHIVE_DIR = ROOT / "data" / "audits" / "workflow_returns"
FEED = ROOT / "data" / "reports" / "whats-next-feed.jsonl"
SEEN = ROOT / "data" / "reports" / ".whats_next_seen.json"
BOARD = ROOT / "PROJECT-BOARD.md"
BOARD_ARCHIVE_DIR = ROOT / "data" / "board-archive"
CANARY_STAMP = ROOT / "data" / "reports" / ".canary_last_alert"
CANARY_LOG = ROOT / "data" / "reports" / "board-canary-alerts.log"

SENTINEL_BEGIN = "<!-- PROJECT-BOARD:GENERATED §0 — DO NOT HAND-EDIT (generated by tools/whats_next_to_board.py from data/audits/workflow_returns/*) — BEGIN -->"
SENTINEL_END = "<!-- PROJECT-BOARD:GENERATED §0 — END -->"

REQUIRED_FIELDS = ("project", "phase", "pct", "next_move", "blocked_on")


def _now() -> _dt.datetime:
    return _dt.datetime.now(_dt.timezone.utc)


def _iso(ts: _dt.datetime) -> str:
    return ts.strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# Extraction — find a valid whats_next in a firewall-return shard, VERBATIM
# ---------------------------------------------------------------------------

def _find_whats_next(record):
    """Return the whats_next dict verbatim, 'NULL' for an explicit honest-null,
    or None if the shard simply doesn't carry the field (pre-contract shard)."""
    if not isinstance(record, dict):
        return None
    if "whats_next" in record:
        return record["whats_next"] if record["whats_next"] is not None else "NULL"
    # one level under the common wrappers only — no deep fishing
    for wrapper in ("result", "return", "firewall_return", "tool_response", "synthesis"):
        inner = record.get(wrapper)
        if isinstance(inner, dict) and "whats_next" in inner:
            return inner["whats_next"] if inner["whats_next"] is not None else "NULL"
    return None


def _valid(wn) -> bool:
    if not isinstance(wn, dict):
        return False
    if not all(k in wn for k in REQUIRED_FIELDS):
        return False
    if not isinstance(wn.get("pct"), int):
        return False
    return True


def _shard_ts(record, path: Path) -> str:
    for key in ("ts", "timestamp", "generated_at"):
        v = record.get(key) if isinstance(record, dict) else None
        if isinstance(v, str) and v:
            return v
    return _iso(_dt.datetime.fromtimestamp(path.stat().st_mtime, _dt.timezone.utc))


def _shard_owner(record) -> str:
    if isinstance(record, dict):
        for key in ("owner", "lead", "vertical", "workflow", "source"):
            v = record.get(key)
            if isinstance(v, str) and v:
                return v
    return "—"


# ---------------------------------------------------------------------------
# --sweep
# ---------------------------------------------------------------------------

def sweep(since_hours: float | None) -> int:
    """Sweep archive shards -> append new whats_next rows to the feed ledger."""
    seen = {}
    if SEEN.exists():
        try:
            seen = json.loads(SEEN.read_text())
        except Exception:
            seen = {}

    cutoff = None
    if since_hours is not None:
        cutoff = _now().timestamp() - since_hours * 3600

    appended = 0
    FEED.parent.mkdir(parents=True, exist_ok=True)
    shards = sorted(ARCHIVE_DIR.glob("*/*.json")) if ARCHIVE_DIR.exists() else []
    with FEED.open("a", encoding="utf-8") as feed:
        for shard in shards:
            rel = str(shard.relative_to(ROOT))
            if rel in seen:
                continue
            if cutoff is not None and shard.stat().st_mtime < cutoff:
                continue
            try:
                record = json.loads(shard.read_text(encoding="utf-8"))
            except Exception as e:
                print(f"[sweep] SKIP unparseable shard {rel}: {e}", file=sys.stderr)
                seen[rel] = "unparseable"
                continue
            wn = _find_whats_next(record)
            if wn is None:
                seen[rel] = "no-whats-next"
                continue
            if wn == "NULL":
                seen[rel] = "honest-null"          # §26.5 — positive omission, no row
                continue
            if not _valid(wn):
                print(f"[sweep] SKIP invalid whats_next in {rel} (missing fields / non-int pct)",
                      file=sys.stderr)
                seen[rel] = "invalid"
                continue
            row = {
                "ts": _shard_ts(record, shard),
                "owner": _shard_owner(record),
                "source_shard": rel,
                # VERBATIM carry — the five fields exactly as the doer-mind judged them
                "whats_next": {k: wn[k] for k in REQUIRED_FIELDS},
            }
            feed.write(json.dumps(row, ensure_ascii=False) + "\n")
            seen[rel] = "fed"
            appended += 1

    SEEN.write_text(json.dumps(seen, indent=1))
    print(f"[sweep] {appended} new row(s) appended to {FEED.relative_to(ROOT)}")
    return appended


# ---------------------------------------------------------------------------
# Archive-before-remove
# ---------------------------------------------------------------------------

def archive_row(row_cells: list[str], reason: str) -> None:
    """Append a departing board row to the current ISO-week archive file
    BEFORE it leaves PROJECT-BOARD.md. Never raises."""
    try:
        BOARD_ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
        now = _now()
        iso_year, iso_week, _ = now.isocalendar()
        f = BOARD_ARCHIVE_DIR / f"{iso_year}-W{iso_week:02d}-workboard-complete.md"
        if not f.exists():
            f.write_text("# Board archive (archive-before-remove rule)\n\n"
                         "| archived_at | reason | row |\n|---|---|---|\n",
                         encoding="utf-8")
        line = f"| {_iso(now)} | {reason} | {' · '.join(c.strip() for c in row_cells)} |\n"
        with f.open("a", encoding="utf-8") as fh:
            fh.write(line)
    except Exception as e:
        print(f"[archive_row] fail-open: {e}", file=sys.stderr)


# ---------------------------------------------------------------------------
# --regen
# ---------------------------------------------------------------------------

def _humanize(delta_s: float) -> str:
    if delta_s < 90:
        return "just now"
    if delta_s < 3600:
        return f"{int(delta_s // 60)}m ago"
    if delta_s < 86400:
        return f"{delta_s / 3600:.1f}h ago"
    return f"{delta_s / 86400:.1f}d ago"


def _md_escape(s: str) -> str:
    """Pipe-escape ONLY (table integrity). Content itself is carried verbatim."""
    return str(s).replace("|", "\\|").replace("\n", " ")


def regen() -> int:
    """Rebuild the §0 block from the feed ledger. Upsert one row per project;
    most-recent ts wins. Archive any row that leaves the board."""
    rows = {}
    if FEED.exists():
        for line in FEED.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                r = json.loads(line)
                wn = r["whats_next"]
                proj = wn["project"]
            except Exception:
                continue
            prev = rows.get(proj)
            if prev is None or r.get("ts", "") >= prev.get("ts", ""):
                rows[proj] = r

    if not BOARD.exists():
        print(f"[regen] no {BOARD.name} at {ROOT} — nothing to do", file=sys.stderr)
        return 1
    text = BOARD.read_text(encoding="utf-8")
    if SENTINEL_BEGIN not in text or SENTINEL_END not in text:
        print("[regen] sentinels not found in PROJECT-BOARD.md — refusing to touch it",
              file=sys.stderr)
        return 1

    # archive-before-remove: any project on the current board but absent from
    # the regenerated set gets archived first
    old_block = text.split(SENTINEL_BEGIN, 1)[1].split(SENTINEL_END, 1)[0]
    for m in re.finditer(r"^\|\s*\*\*(.+?)\*\*\s*\|(.*)\|\s*$", old_block, re.M):
        proj = m.group(1)
        if proj not in rows:
            archive_row([proj] + [c for c in m.group(2).split("|")],
                        reason="transport-regen-dropped")

    now = _now()
    lines = [
        "",
        "> **GENERATED VIEW** — this region is a pure function of `data/reports/whats-next-feed.jsonl` (which is itself a pure function of `data/audits/workflow_returns/YYYY-MM/*.json` firewall-return shards). It is NOT hand-maintained. A stale ledger drifts this board on sight; a regen fixes it.",
        "",
        f"**LAST-GENERATED:** {_iso(now)}",
        "**AGE:** just now",
        "",
        "| Project | Phase | % | Next Move | Blocked | Owner | Last Fire |",
        "|---|---|---|---|---|---|---|",
    ]
    for proj in sorted(rows):
        r = rows[proj]
        wn = r["whats_next"]
        lines.append(
            f"| **{_md_escape(wn['project'])}** | {_md_escape(wn['phase'])} | {wn['pct']} "
            f"| {_md_escape(wn['next_move'])} | {_md_escape(wn['blocked_on'])} "
            f"| {_md_escape(r.get('owner', '—'))} | {_md_escape(r.get('ts', ''))} |"
        )
    lines.append("")

    new_text = (text.split(SENTINEL_BEGIN, 1)[0] + SENTINEL_BEGIN + "\n"
                + "\n".join(lines) + "\n" + SENTINEL_END
                + text.split(SENTINEL_END, 1)[1])
    BOARD.write_text(new_text, encoding="utf-8")
    print(f"[regen] board regenerated: {len(rows)} project row(s)")
    return 0


# ---------------------------------------------------------------------------
# --canary-check
# ---------------------------------------------------------------------------

def canary_check(max_age_hours: float, realert_hours: float) -> int:
    """Alert (log + stdout) if the board froze while projects sit on the frontier.
    Fail-open: any internal error exits 0 silently-ish."""
    try:
        if not BOARD.exists():
            return 0
        text = BOARD.read_text(encoding="utf-8")
        m = re.search(r"\*\*LAST-GENERATED:\*\*\s*(\S+)", text)
        if not m or not m.group(1).startswith("20"):
            return 0  # newborn board, never generated — nothing to alert on
        try:
            gen = _dt.datetime.strptime(m.group(1), "%Y-%m-%dT%H:%M:%SZ").replace(
                tzinfo=_dt.timezone.utc)
        except ValueError:
            return 0
        block = text.split(SENTINEL_BEGIN, 1)[1].split(SENTINEL_END, 1)[0]
        n_rows = len(re.findall(r"^\|\s*\*\*", block, re.M))
        age_h = (_now() - gen).total_seconds() / 3600
        if age_h <= max_age_hours or n_rows == 0:
            print(f"[canary] OK — age {age_h:.1f}h, {n_rows} row(s)")
            return 0
        # rate-limit re-alerts
        if CANARY_STAMP.exists():
            last = _dt.datetime.fromtimestamp(CANARY_STAMP.stat().st_mtime,
                                              _dt.timezone.utc)
            if (_now() - last).total_seconds() < realert_hours * 3600:
                return 0
        msg = (f"{_iso(_now())} BOARD-CANARY TRIPPED: PROJECT-BOARD.md frozen "
               f"{age_h:.1f}h (> {max_age_hours}h) with {n_rows} project(s) on the "
               f"frontier — workflows may be silently failing. "
               f"Run: python3 tools/whats_next_to_board.py --sweep --regen")
        print(msg)
        CANARY_LOG.parent.mkdir(parents=True, exist_ok=True)
        with CANARY_LOG.open("a", encoding="utf-8") as fh:
            fh.write(msg + "\n")
        CANARY_STAMP.touch()
        return 2
    except Exception as e:
        print(f"[canary] fail-open: {e}", file=sys.stderr)
        return 0


# ---------------------------------------------------------------------------
# --self-test  (runs the whole pipeline in a temp root; asserts verbatim carry)
# ---------------------------------------------------------------------------

def self_test() -> int:
    global ROOT, ARCHIVE_DIR, FEED, SEEN, BOARD, BOARD_ARCHIVE_DIR, CANARY_STAMP, CANARY_LOG
    with tempfile.TemporaryDirectory(prefix="whats-next-selftest-") as tmp:
        ROOT = Path(tmp)
        ARCHIVE_DIR = ROOT / "data" / "audits" / "workflow_returns"
        FEED = ROOT / "data" / "reports" / "whats-next-feed.jsonl"
        SEEN = ROOT / "data" / "reports" / ".whats_next_seen.json"
        BOARD = ROOT / "PROJECT-BOARD.md"
        BOARD_ARCHIVE_DIR = ROOT / "data" / "board-archive"
        CANARY_STAMP = ROOT / "data" / "reports" / ".canary_last_alert"
        CANARY_LOG = ROOT / "data" / "reports" / "board-canary-alerts.log"

        BOARD.write_text(SENTINEL_BEGIN + "\n\n(empty)\n\n" + SENTINEL_END + "\n",
                         encoding="utf-8")
        shard_dir = ARCHIVE_DIR / "2026-07"
        shard_dir.mkdir(parents=True)
        wn = {"project": "self-test-project",
              "phase": "Phase 9 — assert | verbatim, pipes included",
              "pct": 73,
              "next_move": "Do exactly THIS, verbatim — including `weird` chars & 100% of punctuation",
              "blocked_on": "none"}
        (shard_dir / f"{uuid.uuid4()}.json").write_text(json.dumps(
            {"ts": "2026-07-09T00:00:00Z", "owner": "selftest-lead", "whats_next": wn}),
            encoding="utf-8")
        # an honest-null shard must NOT create a row (§26.5)
        (shard_dir / f"{uuid.uuid4()}.json").write_text(json.dumps(
            {"ts": "2026-07-09T00:00:01Z", "whats_next": None,
             "whats_next_omit_reason": "self-test"}), encoding="utf-8")

        assert sweep(None) == 1, "expected exactly 1 fed row (null shard skipped)"
        assert sweep(None) == 0, "sweep must be idempotent (seen-set)"
        assert regen() == 0
        board = BOARD.read_text(encoding="utf-8")
        # verbatim assertion: every field byte-equal after pipe-escape unwrap
        row = json.loads(FEED.read_text().splitlines()[0])
        assert row["whats_next"] == wn, "feed row is NOT verbatim vs the shard"
        assert "self-test-project" in board and "73" in board
        assert _md_escape(wn["next_move"]) in board, "board cell not verbatim (modulo pipe-escape)"
        assert "self-test" not in json.dumps(  # null shard produced no feed row
            [json.loads(l)["whats_next"]["project"] for l in FEED.read_text().splitlines()][1:])
        assert canary_check(4, 6) == 0  # freshly generated → OK
        print("SELF-TEST PASS: sweep idempotent, honest-null skipped, verbatim carry verified")
    return 0


# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--sweep", action="store_true")
    ap.add_argument("--sweep-since-hours", type=float, default=None,
                    help="implies --sweep; only shards younger than N hours")
    ap.add_argument("--regen", action="store_true")
    ap.add_argument("--canary-check", action="store_true")
    ap.add_argument("--max-age-hours", type=float, default=4.0)
    ap.add_argument("--realert-hours", type=float, default=6.0)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()
    rc = 0
    if args.sweep or args.sweep_since_hours is not None:
        sweep(args.sweep_since_hours)
    if args.regen:
        rc = regen() or rc
    if args.canary_check:
        rc = canary_check(args.max_age_hours, args.realert_hours) or rc
    if not any([args.sweep, args.sweep_since_hours is not None, args.regen,
                args.canary_check]):
        ap.print_help()
    return rc


if __name__ == "__main__":
    sys.exit(main())
